import curses


KEY_UP = curses.KEY_UP
KEY_DOWN = curses.KEY_DOWN
KEY_LEFT = curses.KEY_LEFT
KEY_RIGHT = curses.KEY_RIGHT

KEYS_ARROW = {KEY_UP, KEY_DOWN, KEY_LEFT, KEY_RIGHT}

KEY_ESC = 27
KEY_ALT = KEY_ESC
KEY_SPACE = 32
KEY_ENTER = 10
KEY_DELETE = 127
